name: actionlint
 
on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
 
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: lint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.SAML_GITHUB_TOKEN }}
