name: Get credentials
on:
  workflow_dispatch:
      

jobs:
  destroy-environment:
    name: Bash test
    runs-on: ubuntu-latest

    steps:
      - name: Login via Azure CLI
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: list out creds
        shell: bash
        run: |
          echo "hello" 
   
