name: Get credentials
on:
  workflow_dispatch:
      

jobs:
  destroy-environment:
    name: Bash test
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.SP_PASSWORD }}
      ARM_TENANT_ID: bd5c6713-7399-4b31-be79-78f2d078e543
    environment:
      name: deveun
 
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.SP_PASSWORD }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}", "tenantId": "6657ffad-1d2b-49a2-9a57-4826941cd6d8"}'

      - name: list out creds
        shell: bash
        run: |
          DEPLOYMENT_OUTPUTS=$(az appservice plan list --query "[].{name:name, resourceGroup:resourceGroup, numberOfSites:numberOfSites} [? contains(name,'dev-pr-')]" )
          echo $output
  
          echo 'convert deployment outputs to outputs'
          echo $DEPLOYMENT_OUTPUTS | jq -c '. | to_entries[] | [.key, .value.value]' |
          while IFS=$"\n" read -r c; do
          echo $c
           OUTPUT_NAME=$(echo "$c" | jq -r '.[0]')
           OUTPUT_VALUE=$(echo "$c" | jq -r '.[1]')
            echo "setting output $OUTPUT_NAME=$OUTPUT_VALUE"
            echo "::set-output name=$OUTPUT_NAME::$OUTPUT_VALUE"
          done
