name: Create SPN
on:
  workflow_dispatch:
 
jobs:
  destroy-environment:
    name: Bash test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
        SP_PASSWORD: ${{ secrets.SP_PASSWORD }}
      run: |
        echo $SP_CLIENT_ID >> secrets.txt
        echo $SP_PASSWORD >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
         
