name: Test Secrets
on:
  workflow_dispatch:
 
jobs:
  first-job:
    name: Deploy application to production
    runs-on: ubuntu-latest
    environment:
      name: Prod
    strategy:
      fail-fast: false
      matrix:
        app: [onyx-sandbox]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Format App name
        id: get-app-name
        run: |
          appName=`echo ${{ matrix.app }} | tr '-' '_' | tr [a-z] [A-Z]`
          echo $appName
          echo "APP_NAME=$appName" >> $GITHUB_ENV
      - name: generate app-specific variable names
        id: get-vars
        run: |
          echo "BACKEND_CONFIG=${{ format('{0}_BACKEND_CONFIG', env.APP_NAME) }}" >> $GITHUB_ENV
          echo "BACKEND_VALUE=${{ secrets[env.BACKEND_CONFIG] }}"  >> $GITHUB_ENV
      - name: E2E tests
        env:
           BACKEND_CONFIG: ${{ secrets[env.BACKEND_CONFIG] }}
           BACKEND_VALUE: ${{ secrets[env.BACKEND_VALUE] }}
           DF_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
  
        run: |
            echo $BACKEND_CONFIG
            echo $BACKEND_VALUE | sed 's/./& /g'
            echo $DF_TOKEN | sed 's/./& /g'
           
